name: test-job
on: push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
      - name: lint the code
        run: eslint --ext .jsx --fix src
      - name: test the code
        run: vitest run
      - name: build the code
        run: vite build
    
