name: test-job
on: push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm install
        working-directory: ./04\ Practice\ Project\ (Start)
      - name: lint the code
        run: npm run lint
        working-directory: ./04\ Practice\ Project\ (Start)
        
      - name: test the code
        run: npm test
        working-directory: ./04\ Practice\ Project\ (Start)
      
      - name: build the code
        run: npm run build
        working-directory: ./04\ Practice\ Project\ (Start)
      
    
